"""Cut the two typefaces down to what the page actually uses.

Run through assets/build.py rather than directly.

The faces are shipped inside the binary instead of fetched from a font host.
Fetching one would be a request to somebody else's server, and this page tells
the reader that nothing was sent anywhere, which has to stay true. It also
means the page looks the same with the network unplugged, which is a normal way
to run a tool that reads local history.

Subsetting is what makes that affordable: the two files arrive at 640 KB
together and leave at a fraction of it, because a page needs Latin text and
almost nothing else.
"""

import base64
import os

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "fonts")

# Everything the page can put on screen. Prompts are the user's own words, so
# the body face keeps the whole of Latin-1 plus the punctuation people actually
# type, including the quotes and dashes editors substitute silently.
BODY = (
    "".join(chr(c) for c in range(0x20, 0x7F))
    + "".join(chr(c) for c in range(0xA0, 0x100))
    + "‘’“”–—…•·"
    + "→↑↓↵▸▾●○"
)

# The display face only ever sets a project name and a date, so it needs far
# less. Names come from directories on this machine, which are Latin in
# practice, and anything outside this falls through to the stack behind it.
DISPLAY = (
    "".join(chr(c) for c in range(0x20, 0x7F))
    + "".join(chr(c) for c in range(0xC0, 0x100))
    + "‘’“”–—"
)


def pin(path, axes):
    """Freeze a variable font to one instance.

    The display face has four axes and is used at exactly one setting, so
    carrying the others is weight for nothing.
    """
    font = TTFont(path)
    if "fvar" in font:
        font = instancer.instantiateVariableFont(font, axes, updateFontNames=False)
    return font


def cut(font, text, name):
    """Subset a font to a set of characters and return it as woff2."""
    options = subset.Options()
    options.layout_features = ["kern", "liga", "calt", "tnum"]
    options.desubroutinize = True
    options.drop_tables += ["DSIG"]
    options.notdef_outline = False
    options.recalc_bounds = True

    subsetter = subset.Subsetter(options=options)
    subsetter.populate(text=text)
    subsetter.subset(font)

    font.flavor = "woff2"
    out = os.path.join(SRC, name)
    font.save(out)
    return out


def embed(path):
    """Return a font as a data URI, ready to drop into a stylesheet."""
    with open(path, "rb") as f:
        return "data:font/woff2;base64," + base64.b64encode(f.read()).decode("ascii")


def build():
    """Produce the @font-face rules the stylesheet imports."""
    faces = []
    total = 0

    # Fraunces at one optical size and weight. The soft axis is left at zero
    # and the wonk axis on, which is the setting that gives the face its
    # slightly agricultural character.
    display = pin(
        os.path.join(SRC, "fraunces.ttf"),
        {"opsz": 72, "wght": 600, "SOFT": 0, "WONK": 1},
    )
    path = cut(display, DISPLAY, "display.woff2")
    total += os.path.getsize(path)
    faces.append(("Bough Display", 600, "normal", path))

    for weight, filename in ((400, "JetBrainsMono-Regular.ttf"), (500, "JetBrainsMono-Medium.ttf")):
        body = TTFont(os.path.join(SRC, filename))
        out = cut(body, BODY, f"body-{weight}.woff2")
        total += os.path.getsize(out)
        faces.append(("Bough Mono", weight, "normal", out))

    rules = []
    for family, weight, style, path in faces:
        rules.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            f"  font-weight: {weight};\n"
            f"  font-style: {style};\n"
            "  font-display: swap;\n"
            f"  src: url({embed(path)}) format('woff2');\n"
            "}"
        )

    css = (
        "/* Generated by assets/build.py. Do not edit.\n"
        " *\n"
        " * The faces are inside the binary rather than fetched from a font\n"
        " * host, so the page holds its design with no network and makes no\n"
        " * request to anyone. Subset to Latin and the punctuation people type.\n"
        " */\n\n" + "\n\n".join(rules) + "\n"
    )

    print(f"  {'fonts':16} {total / 1024:5.1f} KB subset, {len(css) / 1024:5.1f} KB as base64")
    return css
